P8105 HW 2
================
2026-10-01

Pull packages

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### Problem 1

Read and clean data, retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance. Convert Yes and No to logical variable.

``` r
transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
           na = "") |>
           janitor::clean_names() |>
  select(line:entry, vending, entrance_type, ada) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE),
    entry = as.logical(entry),
    vending = case_match(
      vending,
      "YES" ~ TRUE,
      "NO" ~ FALSE),
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
    )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
# entry and vending have YES and NO values

# using str(transit_df) in console, found that the route columns variable types don't match, will need the mutate
```

line represents the physical subway line the subway route runs through,
such as the West End, or Jerome in the Bronx. station_name indicates the
name of a single station on the line. Each route column indicates
indicates what route is served, such as the Q train, or 4/5/6 trains. If
the station services less than 11 routes, the value is NA.
station_latitude / longitude indicates the location of the subway
station. entrance_type indicates the station’s entrance type. Entry
indicates whether or not the entrance type is also a point of entry. If
false, it is an exit. Vending indicates if there is a MTA card vending
machine at the entrance and ada notes whether or not it is ADA
(Americans with Disabilities Act) compliant. So far, I have told
`read_csv` to treat blank values as NA, cleaned the column names to be
all lower case and standardized with `janitor::clean_names()`, selected
the columns of interest with `select()`, and used the `mutate()`
function to transform the character variables in entry and vending to
logical variables. route8, 9, 10, and 11 column types were converted to
characters since they are subway route names.

``` r
# number of distinct stations 

transit_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

``` r
# number of stations ADA compliant

transit_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

``` r
# proportion of entrances/ exits without vending allow entrance

transit_df |>
  filter(vending == FALSE) |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

There are 465 distinct stations. 84 stations are ada compliant. The
proportion of station entrances/ exits without vending allow entrance is
0.3770492.

Reformat data so route number and route name are distinct variables

``` r
transit_long = 
  transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

Distinct stations serve the A train. Of those, ADA compliant?

``` r
transit_long |> 
  filter(route_name == "A") |>
  distinct(line, station_name, route_name) |>
  nrow()
```

    ## [1] 60

``` r
# ADA compliant

transit_long |>
  filter(route_name == "A") |>
  filter(ada == TRUE) |>
  distinct(line, station_name, route_name) |>
  nrow()
```

    ## [1] 17

60 distinct stations serve the A train. Only 17 of these 60 stations are
ADA compliant.

### Problem 2

``` r
trash_df = 
  readxl:: read_excel(
  "./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  skip = 1, #omit unnecessary rows
  range = "A2:N710") |>
  janitor::clean_names() |> #cleaning names
  filter(!is.na(dumpster)) |> #remove last NA column using dumpster
  mutate(
    sports_balls = as.integer(round(sports_balls, digits=0)), #round balls to nearest integer
    wheel_type = "mr_trash",
    year = as.integer(year)
  )

prof_df = 
  readxl::read_excel(
    "./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  skip = 1, 
  range = "A2:M135") |>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> #no sports balls
  mutate(
    wheel_type = "professor_trash"
  )

gwynnda_df = 
  readxl::read_excel(
    "./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynns Falls Trash Wheel",
  skip = 1, 
  range = "A2:L352") |>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(
    wheel_type = "gwynnda"
  )

trash_tidy = 
  bind_rows(trash_df, prof_df, gwynnda_df) |>
  relocate(wheel_type) |>
  mutate(
    month = str_to_lower(month)
  )
```

There are 1188 total observations in the new tidy dataset. Of these 1188
observations, 707 are from Mr. Trash Wheel, 132 are from Professor Trash
Wheel, and 349 are from the Gwynns Falls Trash Wheel. There are 1187
distinct dumpsters in total. The column month will output all 12 months
of the year: may, june, july, august, september, october, november,
december, january, february, march, and april. The year column contains
years between 2014 and 2025 weight_tons lists the total weight of trash
collected by the trash wheel at the given observation. Variables such
cigarette_butts, bottles, sports_balls, and wrappers count the the
amount of each trash type collected by the trash wheel at the time of
observation. The total weight of trash collected by Professor Trash
Wheel was 282.26 tons. In June of 2022, Gwynnda collected 18,120
cigarette butts.
